const data = [
  {
    title: "Basics of learning team management",
    instructor: "cPerson1.png",
    role: "IT Manager",
    participants: 120,
    price: "$120",
    videos: 25,
    image: "c1.png",
  },
  {
    title: "Learn basic database structure",
    instructor: "cPerson2.png",
    role: "Data Science",
    participants: 55,
    price: "$180",
    videos: 20,
    image: "c2.png",
  },
  {
    title: "Create dynamic website with basic PHP",
    instructor: "cPerson3.png",
    role: "Programmer",
    participants: 98,
    price: "$135",
    videos: 20,
    image: "c3.png",
  },
  {
    title: "Introduction to Cloud Computing",
    instructor: "cPerson2.png",
    role: "Cloud Engineer",
    participants: 200,
    price: "$150",
    videos: 30,
    image: "c1.png",
  },
  {
    title: "Mastering JavaScript",
    instructor: "cPerson1.png",
    role: "Frontend Developer",
    participants: 300,
    price: "$200",
    videos: 40,
    image: "c2.png",
  },
  {
    title: "Advanced Python Programming",
    instructor: "cPerson2.png",
    role: "Software Engineer",
    participants: 250,
    price: "$175",
    videos: 35,
    image: "c3.png",
  },
];

export default data;
